---
apiVersion: consul-release-controller.nicholasjackson.io/v1
kind: Release
metadata:
  name: payments
  namespace: default
spec:
  releaser:
    pluginName: "consul"
    config:
      consulService: "payments"
#     namespace: "mynamespace"
#     partition: "mypartition"
  runtime:
    pluginName: "kubernetes"
    config:
      deployment: "payments-deployment"
  strategy:
    pluginName: "canary"
    config:
      initialDelay: "30s"
      initialTraffic: 10
      interval: "30s"
      trafficStep: 20
      maxTraffic: 100
      errorThreshold: 5
  monitor:
    pluginName: "prometheus"
    config:
      address: "http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090"
      queries:
        - name: "request-success"
          preset: "envoy-request-success"
          min: 99
        - name: "request-duration"
          preset: "envoy-request-duration"
          min: 20
          max: 200
#       - name: "mycustom"
#         min: 20
#         max: 200
#         query: |
#           histogram_quantile(
#             0.99,
#             sum(
#               rate(
#                 envoy_cluster_upstream_rq_time_bucket{
#                   namespace="{{ .Namespace }}",
#                   envoy_cluster_name="local_app",
#                   pod=~"{{ .Name }}-[0-9a-zA-Z]+(-[0-9a-zA-Z]+)"
#                 }[{{ .Interval }}]
#               )
#             ) by (le)
#           )