name: Go

on: [push]

jobs:

  check_labels:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2

      - id: check_pr_labels
        name: Check PR labels
        uses: nicholasjackson/check-pr-labels-on-push-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["patch", "minor", "major"]'
          match-any: 'true'
      
      - name: Echo test
        run: |
          echo "${{ steps.check_pr_labels.outputs.labels }}"
          echo "${{ fromJson(steps.check_pr_labels.outputs.labels)[0] }}"

      - name: Cancel Workflow
        if: ${{ steps.check_pr_labels.outputs.result == 'false' }}
        uses: andymckay/cancel-action@0.2

      - name: Send status to Discord
        if: ${{ steps.check_pr_labels.outputs.result == 'false' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: "Unable to release new version, ensure that all PRs are labeled with a valid release label (patch, minor, major)"

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  check-kubebuilder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup Kubebuilder
      run: |
        os=$(go env GOOS)
        arch=$(go env GOARCH)
        # download kubebuilder and extract it to tmp
        curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v3.1.0/kubebuilder_linux_amd64 \
             -o /tmp/kubebuilder
        sudo mv /tmp/kubebuilder /usr/local/bin/kubebuilder
   
    - name: Check Kubebuilder can generate CRDs
      run: cd kubernetes/controller && make manifests
    
    - name: Check Kubebuilder can generate deep copy objects
      run: cd kubernetes/controller && make generate
   
  functional_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags:
          - "@k8s_canary_existing"
          - "@k8s_canary_none"
          - "@k8s_canary_rollback"
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup Functional Tests
      run: |
        curl https://shipyard.run/install | bash
    
    - name: Run Functional Tests
      run: |
        cd functional_tests && go run . --godog.tags="${{ matrix.tags }}"
      
    - name: Send status to Discord
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        description: "Executed functional test: ${{ matrix.tags }}"

  dev-docker:
    name: Build development Docker image
    runs-on: ubuntu-latest
    needs:
      - build
      - functional_tests
    if: ${{ github.ref == 'refs/heads/dev' }}

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - uses: actions/checkout@v2
      
    - name: Build and Push Docker Image
      run: |
        make build_docker
    
    - name: Send status to Discord
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        description: "Built new Docker image"

  release:
    name: Build production Docker image and release Helm chart
    runs-on: ubuntu-latest
    needs:
      - build
      - functional_tests
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - uses: actions/checkout@v2

    - id: check_pr_labels
      uses: nicholasjackson/check-pr-labels-on-push-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        labels: '["patch", "minor", "major"]'
        match-any: 'true'

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} 
        dry_run: true
        default_bump: ${{ fromJson(steps.check_pr_labels.outputs.labels)[0] }}
     
    - name: Build and Push Docker Image
      run: |
        make build_docker
      env:
        VERSION_ENV: ${{ steps.next_version.outputs.new_version }}
    
    - name: Generate the Helm release
      run: |
        make helm_release
      env:
        VERSION_ENV: ${{ steps.next_version.outputs.new_version }}

    - name: Commit changes
      uses: EndBug/add-and-commit@v8
      with:
        default_author: github_actions
        message: 'Update helm chart to version ${{ steps.next_version.outputs.new_version }}'
        add: '*.yaml' 
    
    - name: Bump version and push tag
      id: create_tag
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} 
        default_bump: ${{ fromJson(steps.check_pr_labels.outputs.labels)[0] }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.next_version.outputs.new_tag }}
        token: ${{ secrets.GH_TOKEN }}
        files: | 
          ./consul-release-controller-${{ steps.next_version.outputs.new_version }}.tgz

    - name: Deploy Github pages
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.
    
    - name: Send status to Discord
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        description: "Built new Docker image"
